# test: skip

import sys {stdout, File, open, read, write, O_RDONLY, CreateMode}

fn main() {
    with! let fd = open(File(str(__filename__), O_RDONLY, CreateMode(0))) {
        /* This is allocating a small buffer size just to test the
         * looping behavior and that we aren't off by one, etc... */
        let buffer = alloc(14)

        while True {
            let cb = read(fd, buffer, 14)
            if cb <= 0 {
                break
            }
            match! write(stdout, Buffer(buffer, cb)) {
                Right(errno) {
                    panic("Failed to write to stdout with ${errno}")
                }
            }
        }
    }
}

# expect: It printed all the way down here.
